spring:
  application:
    name: reservation
  cache:
    type: redis
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/reservationdb
    username: reservation_user
    password: strongpassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  liquibase:
    contexts: ${spring.profiles.active}
    database-change-log-table: Z_LIQ_CHANGELOG
    database-change-log-lock-table: Z_LIQ_CHANGELOG_LOCK
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
reservation:
  queue:
    batch-size: 10
    poll-interval-ms: 100
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
